apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: syfosmarena
  namespace: default
  labels:
    team: "teamsykefravr"
spec:
  name: "syfosmarena"
  image: "repo.adeo.no:5443/syfo/syfosmarena:@@VERSION@@"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  vault:
    enabled: true
  ingress:
    disabled: false
  env:
  - name: MQ_HOST_NAME
    value: {{MQ_HOST_NAME}}
  - name: MQ_PORT
    value: '{{MQ_PORT}}'
  - name: MQ_GATEWAY_NAME
    value: {{MQ_GATEWAY_NAME}}
  - name: MQ_CHANNEL_NAME
    value: {{MQ_CHANNEL_NAME}}
  - name: KAFKA_BOOTSTRAP_SERVERS_URL
    value: {{KAFKA_BOOTSTRAP_SERVERS_URL}}
  - name: MQ_ARENA_QUEUE
    value: {{MQ_ARENA_QUEUE}}
