apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: syfosmarena-stream-alerts
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  receivers:
    slack:
      channel: '#sykmelding-alerts'
      #prependText: '<!here> | '
  alerts:
    - alert: syfosmarena-stream er nede
      expr: up{app="syfosmarena-stream", job="kubernetes-pods"} == 0
      for: 5m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
    - alert: syfosmarena-stream-kafka-offset
      expr: kafka_consumergroup_group_sum_lag{group=~"teamsykmelding.syfosmarena-stream_stream_"} > 100
      for: 1m
      description: "syfosmarena-stream kafka-lag er høyt"
      action: "Sjekk om syfosmarena-stream leser fra kafka"
      sla: respond within 1h, during office hours
      severity: danger