name: Deploy stream to dev
on:
  push:
    branches:
      - '*'
      - '!master'
    paths:
      - 'syfosmarena-stream/**'
      - '.github/workflows/stream**'
      - 'build.gradle.kts'

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup gradle dependency cache
        uses: actions/cache@v3
        with:
          path: |
            ~../.gradle/caches
            ~../.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run tests
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew :syfosmarena-stream:test
      - name: Build jar
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew :syfosmarena-stream:shadowJar -x test
      - name: stream-docker-build-push
        uses: nais/docker-build-push@v0
        id: stream-docker-build-push
        with:
          team: teamsykmelding
          dockerfile: syfosmarena-stream/Dockerfile
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Deploy to Preprod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_TEAMSYKMELDING }}
          CLUSTER: dev-gcp
          RESOURCE: syfosmarena-stream/naiserator-dev.yaml
          VAR: image=${{ steps.stream-docker-build-push.outputs.image }}