apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmarena
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1792Mi
    requests:
      cpu: 100m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfosmarena
        mountPath: /secrets/serviceuser
  kafka:
    pool: nav-prod
  env:
    - name: MQ_HOST_NAME
      value: a01apvl270.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS03
    - name: MQ_CHANNEL_NAME
      value: P_SYFOSMARENA
    - name: MQ_ARENA_QUEUE
      value: QA.P414.FS06_ARENA